"""
badges.py — Orbit Badge Definitions
Single source of truth for all 36 badges.
Each badge: id, name, description, category, trigger, rarity, icon emoji, glow color
"""

BADGES = {
    # ─── ACTIVITY ───────────────────────────────────────────────────────────
    "first_analysis": {
        "id": "first_analysis",
        "name": "First Analysis",
        "description": "Ran your first coin analysis.",
        "category": "activity",
        "trigger": "auto",  # awarded in /analyze or /stream route
        "rarity": "common",
        "emoji": "🔭",
        "color": "#7eb8f7",
    },
    "degen_starter": {
        "id": "degen_starter",
        "name": "Degen Starter",
        "description": "Ran 10 analyses.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "📡",
        "color": "#7eb8f7",
    },
    "analyst": {
        "id": "analyst",
        "name": "Analyst",
        "description": "Ran 50 analyses.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "📊",
        "color": "#a78bfa",
    },
    "signal_machine": {
        "id": "signal_machine",
        "name": "Signal Machine",
        "description": "Ran 200 analyses.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "rare",
        "emoji": "⚡",
        "color": "#f59e0b",
    },
    "first_post": {
        "id": "first_post",
        "name": "First Post",
        "description": "Posted your first forum thread.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "✍️",
        "color": "#7eb8f7",
    },
    "conversationalist": {
        "id": "conversationalist",
        "name": "Conversationalist",
        "description": "Left 25 replies.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "💬",
        "color": "#7eb8f7",
    },
    "veteran": {
        "id": "veteran",
        "name": "Veteran",
        "description": "Account older than 30 days.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "🪖",
        "color": "#7eb8f7",
    },
    "og": {
        "id": "og",
        "name": "OG",
        "description": "One of the first 100 users on Orbit.",
        "category": "activity",
        "trigger": "auto",
        "rarity": "legendary",
        "emoji": "👑",
        "color": "#fbbf24",
    },

    # ─── TRADING & PNL ──────────────────────────────────────────────────────
    "in_the_green": {
        "id": "in_the_green",
        "name": "In The Green",
        "description": "Connected wallet with positive PnL.",
        "category": "trading",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "📈",
        "color": "#34d399",
    },
    "whale": {
        "id": "whale",
        "name": "Whale",
        "description": "Top 10 PnL on the leaderboard.",
        "category": "trading",
        "trigger": "auto",
        "rarity": "rare",
        "emoji": "🐋",
        "color": "#60a5fa",
    },
    "rug_survivor": {
        "id": "rug_survivor",
        "name": "Rug Survivor",
        "description": "Analyzed a coin whose outcome was recorded as a rug.",
        "category": "trading",
        "trigger": "auto",  # checked when outcome is recorded as rug
        "rarity": "uncommon",
        "emoji": "🧯",
        "color": "#f87171",
    },

    # ─── COMMUNITY ──────────────────────────────────────────────────────────
    "social_butterfly": {
        "id": "social_butterfly",
        "name": "Social Butterfly",
        "description": "Followed by 10 people.",
        "category": "community",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "🦋",
        "color": "#c084fc",
    },
    "influencer": {
        "id": "influencer",
        "name": "Influencer",
        "description": "Followed by 50 people.",
        "category": "community",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "📣",
        "color": "#f472b6",
    },
    "helpful": {
        "id": "helpful",
        "name": "Helpful",
        "description": "Received 50 upvotes across posts.",
        "category": "community",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "🤝",
        "color": "#34d399",
    },
    "forum_legend": {
        "id": "forum_legend",
        "name": "Forum Legend",
        "description": "Received 200 upvotes across posts.",
        "category": "community",
        "trigger": "auto",
        "rarity": "rare",
        "emoji": "🏆",
        "color": "#fbbf24",
    },
    "thread_starter": {
        "id": "thread_starter",
        "name": "Thread Starter",
        "description": "Created 10 threads.",
        "category": "community",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "🧵",
        "color": "#7eb8f7",
    },
    "special": {
        "id": "special",
        "name": "Special",
        "description": "Granted by a moderator.",
        "category": "community",
        "trigger": "manual",  # mod grants via mod panel
        "rarity": "rare",
        "emoji": "⭐",
        "color": "#fbbf24",
    },

    # ─── SUBSCRIPTION ───────────────────────────────────────────────────────
    "degen_member": {
        "id": "degen_member",
        "name": "Degen Member",
        "description": "Active Degen subscription.",
        "category": "subscription",
        "trigger": "auto",  # synced from stripe webhook
        "rarity": "uncommon",
        "emoji": "🔥",
        "color": "#fb923c",
    },
    "omega_member": {
        "id": "omega_member",
        "name": "Omega Member",
        "description": "Active Omega subscription.",
        "category": "subscription",
        "trigger": "auto",
        "rarity": "rare",
        "emoji": "🌌",
        "color": "#818cf8",
    },
    "founding_degen": {
        "id": "founding_degen",
        "name": "Founding Degen",
        "description": "One of the first 100 Degen subscribers.",
        "category": "subscription",
        "trigger": "auto",
        "rarity": "legendary",
        "emoji": "🔶",
        "color": "#f59e0b",
    },
    "founding_omega": {
        "id": "founding_omega",
        "name": "Founding Omega",
        "description": "One of the first 100 Omega subscribers.",
        "category": "subscription",
        "trigger": "auto",
        "rarity": "legendary",
        "emoji": "🟣",
        "color": "#a78bfa",
    },

    # ─── SPECIAL / STAFF ────────────────────────────────────────────────────
    "owner": {
        "id": "owner",
        "name": "Owner",
        "description": "Orbit founder.",
        "category": "staff",
        "trigger": "manual",
        "rarity": "legendary",
        "emoji": "🌀",
        "color": "#ffffff",  # white glow
        "glow": True,
    },
    "mod": {
        "id": "mod",
        "name": "Mod",
        "description": "Community moderator.",
        "category": "staff",
        "trigger": "manual",
        "rarity": "rare",
        "emoji": "🛡️",
        "color": "#34d399",
    },
    "beta_tester": {
        "id": "beta_tester",
        "name": "Beta Tester",
        "description": "Had an account before public launch.",
        "category": "staff",
        "trigger": "manual",
        "rarity": "rare",
        "emoji": "🧪",
        "color": "#60a5fa",
    },
    "orbit_dev": {
        "id": "orbit_dev",
        "name": "Orbit Dev",
        "description": "Orbit development team.",
        "category": "staff",
        "trigger": "manual",
        "rarity": "legendary",
        "emoji": "💻",
        "color": "#f472b6",
    },
    "advisor": {
        "id": "advisor",
        "name": "Advisor",
        "description": "Orbit advisor.",
        "category": "staff",
        "trigger": "manual",
        "rarity": "rare",
        "emoji": "🎖️",
        "color": "#fbbf24",
    },

    # ─── SKILL ──────────────────────────────────────────────────────────────
    "early_bird": {
        "id": "early_bird",
        "name": "Early Bird",
        "description": "Analyzed a coin under 5 minutes old.",
        "category": "skill",
        "trigger": "auto",  # check coin age from DexScreener pairCreatedAt
        "rarity": "uncommon",
        "emoji": "🐦",
        "color": "#fde68a",
    },
    "on_a_run": {
        "id": "on_a_run",
        "name": "On A Run",
        "description": "Ran 3 analyses within 1 minute.",
        "category": "skill",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "🏃",
        "color": "#fb923c",
    },
    "purity_seeker": {
        "id": "purity_seeker",
        "name": "Purity Seeker",
        "description": "Analyzed 10 coins with a purity score above 80.",
        "category": "skill",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "💎",
        "color": "#67e8f9",
    },

    # ─── FUN / RARE ─────────────────────────────────────────────────────────
    "cupsey_warning": {
        "id": "cupsey_warning",
        "name": "Cupsey Warning",
        "description": "Bought a coin Cupsey shilled.",
        "category": "fun",
        "trigger": "manual",
        "rarity": "legendary",
        "emoji": "☕",
        "color": "#f87171",
    },
    "night_owl": {
        "id": "night_owl",
        "name": "Night Owl",
        "description": "Ran an analysis between 2am and 5am.",
        "category": "fun",
        "trigger": "auto",
        "rarity": "common",
        "emoji": "🦉",
        "color": "#818cf8",
    },
    "grinder": {
        "id": "grinder",
        "name": "Grinder",
        "description": "Ran an analysis 7 days in a row.",
        "category": "fun",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "⚙️",
        "color": "#94a3b8",
    },
    "lucky": {
        "id": "lucky",
        "name": "Lucky",
        "description": "A coin you analyzed hit $1M market cap.",
        "category": "fun",
        "trigger": "auto",  # checked when outcome is recorded
        "rarity": "rare",
        "emoji": "🍀",
        "color": "#34d399",
    },
    "unlucky": {
        "id": "unlucky",
        "name": "Unlucky",
        "description": "Tracked 5 or more rugs or fake coins.",
        "category": "fun",
        "trigger": "auto",
        "rarity": "uncommon",
        "emoji": "💀",
        "color": "#6b7280",
    },
}

BADGE_IDS = list(BADGES.keys())

RARITY_ORDER = ["common", "uncommon", "rare", "legendary"]

# How many badges each tier can equip (displayed on profile)
EQUIP_LIMITS = {
    "free": 1,
    "degen": 3,
    "omega": 5,
}
